version: '3.8'

services:
  bot:
    build: .
    container_name: mechanic-nikitich-bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "bot.py"]
